### PR TITLE
Switch welcome bar to use superstore

### PR DESCRIPTION
**Pull request by i-like-robots**
Superstore is already a dependency of this module.

To fix https://jira.ft.com/browse/NFT-241

### CODE REVIEW

**Comment by matthew-andrews** [comment]
does this mean it'll come back to every who had dismissed it before?

**Comment by i-like-robots** [comment]
I assume it's still getting and setting the same localStorage key... am I mistaken?

**Comment by matthew-andrews** [comment]
ah yes it does.

i wrote that a long time ago

ok carry on.

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
